- source/includes/_intro.md
- source/index.html.md
> fix general introduction and intro sections

- source/includes/_invoices.md
- source/includes/_payment_methods.md
- source/includes/_payments.md
First ShareActor day:
updated documentation in invoice, payment and payment method for our API
> Update documentation for invoice, payment and payment method

- source/includes/_auth.md
> making authorization stuff

- source/includes/_invoices.md
- source/includes/_issuers.md
- source/includes/_payment_methods.md
- source/includes/_payments.md
- source/includes/_users.md
Updating all API headers from examples
> fix all API requests properly

- source/includes/_phone_nr_verification.md
- source/index.html.md
> Phone nr verification

- source/includes/_payments.md
- source/includes/_providers.md
The initial provider creation docs.
I'm not very sure `available_on_bank_holidays` what it means so I need you
> initial provider creation docs

- source/includes/_issuers.md
- source/includes/_products.md
First step for Product docs.
- Create
- get_product_id
> Initial Product creation Docs

- source/includes/_orders.md
> initial order creation docs

- source/includes/_address.md
Initial address creation docs.
-------
`raw` attribute has no description for a moment.
`service_address_id` same
> Initial address creation docs

- source/includes/_users.md
Changes all IDs by [Class_id](#route_file#)
> More similar -  clear IDs - use Class_id with link

- source/includes/_issuers.md
Just add like this:
> Definition
DELETE https://api.shareactor.io/issuers/<issuer_id>
> Example request:
> add more similarity

- source/includes/_plans.md
- source/includes/_subscriptions.md
- source/index.html.md
Documentation for Plan that is coming soon. And I created a new file for the subscription documentation
> Plan documentation

- source/includes/_auth.md
- source/includes/_products.md
- source/includes/_providers.md
- source/includes/_users.md
The docs for Products and Providers are formatted differently than for others.  They have a column for 'type' that the others don't.
> Doc Proofing ToDos

- source/includes/_address.md
- source/includes/_issuers.md
- source/includes/_products.md
- source/includes/_providers.md
- source/includes/_users.md
> fix pagination like definition and example - fix small things

- source/includes/_address.md
- source/includes/_invoices.md
- source/includes/_issuers.md
- source/includes/_orders.md
- source/includes/_payment_methods.md
- source/includes/_payments.md
- source/includes/_phone_nr_verification.md
- source/includes/_plans.md
- source/includes/_products.md
- source/includes/_providers.md
- source/includes/_users.md
Using the proper json type
Deleted the default fields like: Created, updated, etc..
Remove dot on the end of phrase
> Use json types

- source/includes/_subscriptions.md
Initial documentation on the subscription model
> initial subscription documentation

- source/includes/_orders.md
- source/includes/_products.md
- source/includes/_providers.md
- source/includes/_users.md
Try to make sure we are using the same user data (names, email, number, id, addresses...)
> Use same user data

- source/includes/_intro.md
Updated Introduction, add X-Pagination-Total
> add X-Pagination-Total in intro

- source/includes/_intro.md
> add few errors

- source/includes/_address.md
Just add a little description of Address
> add a decription for address

- source/includes/_issuers.md
- source/includes/_plans.md
Result : 
no company confidential 
Just change few things
> Make sure we didn't use confidential company data

- source/includes/_subscriptions.md
A small add after the Subscription PR, and fixed a small typo.
> Subscription PR add

- source/includes/_invoices.md
- source/includes/_orders.md
- source/includes/_payment_methods.md
- source/includes/_payments.md
- source/includes/_plans.md
- source/includes/_products.md
- source/includes/_providers.md
- source/includes/_subscriptions.md
- source/includes/_users.md
Try to update json types in documentation. Not finished yet
> first commit to fix json types in documentation

- source/includes/_resources.md
This will add documentation on how to create resources in bulk.
> resources bulk documentation

- source/includes/_subscriptions.md
When updating the subscriptions, I changed the route to `subscriptions/<id>` instead of `subscriptions/<id>/update`
> update subscriptions update more restfull

- source/includes/_issuers.md
Improve the description of Search and Get list
> Issuers - improve search and get

- source/includes/_issuers.md
- source/includes/_orders.md
Add orders search's description
> Orders and Issuers - add search description

- source/includes/_addresses.md
- source/includes/_auth.md
- source/includes/_invoices.md
Some more of Wesley's edits.On the intro, addresses and invoices
> Wesley edits

- source/includes/_products.md
Add search's description and improve the get's description
> Products - add search and improve get

- source/includes/_invoices.md
- source/includes/_issuers.md
- source/includes/_payment_methods.md
- source/includes/_payments.md
- source/includes/_users.md
Add documentation on Search and improve the get list.
Moreover, name refactoring on `order_by` to `sort`.
> Invoices - improve search get

- source/includes/_users.md
A small improvement on the description of search and get.
> Users - improve search and get description

- source/includes/_intro.md
I'm trying to introduce our Searching and Getting items in the Introduction.
> Intro - add Search and Get in intro

- source/includes/_plans.md
> Wesley edits on plan

- source/includes/_intro.md
Add resources search to list in intro over methods that have the search function.
> add resources to search list in intro

- source/includes/_plans.md
- source/includes/_subscriptions.md
Added new stuff from the plans and subscription.
In particular the part with the company specific plan.
> add new stuff to plan and subscriptions

- source/includes/_auth.md
- source/includes/_orders.md
- source/includes/_payments.md
- source/includes/_products.md
- source/includes/_resources.md
- source/includes/_users.md
> awesome updates to the docs

- source/includes/_orders.md
Remove the `Required` label on a few fields.
> Order - improve the required fields

- source/includes/_payment_methods.md
Add how to create a Stripe payment method.
> Stripe payment method

- source/includes/_labs.md
- source/index.html.md
Initial docs to the DS integration
I made a list of different models, but I only know the name of two of them. So I need some more...
> Initial docs to he DS integration

- source/includes/_metrics.md
- source/includes/_stats.md
- source/index.html.md
Some documentation for the beloved metrics (finally).
> Documentation for metrics

- source/includes/_orders.md
Updated some docs regarding the Order
> Update docs for the order

- source/includes/_invoices.md
An update for the invoice docs.
> update docs for invoices

- source/index.html.md
:warning: it when our Status page will be updated to status.kvass.ai :warning:
> Change the status page link

- source/includes/_plans.md
fix #79 
--- 
I removed the `prorate` and `discount` fields because they don't exist anymore.
> Wrong exmaple Creating Plan

- source/includes/_events.md
fix #80
---
Add all new events and update the model
> Events | Add new events and update model

- source/includes/_coupons.md
- source/index.html.md
> introduce coupons

- source/includes/_payments.md
Add single payment processing to docs
> add single payment to docs

- source/includes/_intro.md
fix #88 
---
Added the Error 415, Unsupported Media Type.
> add the error 415

- source/CNAME
- source/includes/_intro.md
- source/includes/_plans.md
- source/includes/_subscriptions.md
Replace shareactor by kvass and update the domain to reference.kvass.ai
> Update domain `reference.kvass.ai`

- source/includes/_addresses.md
- source/includes/_coupons.md
- source/includes/_events.md
- source/includes/_intro.md
- source/includes/_invoices.md
- source/includes/_issuers.md
- source/includes/_labs.md
- source/includes/_metrics.md
- source/includes/_orders.md
- source/includes/_payment_methods.md
- source/includes/_payments.md
- source/includes/_phone_nr_verification.md
- source/includes/_plans.md
- source/includes/_products.md
- source/includes/_providers.md
- source/includes/_resources.md
- source/includes/_subscriptions.md
- source/includes/_users.md
- source/includes/_webhooks.md
> Update x-share-api-key to x-kvass-api-key

- source/includes/_plans.md
fix #97  
---
New route 
`GET /plans/plan_id/subscriptions`
> Get Subscription form a Plan

- source/includes/_webhooks.md
Docs on how to simulate a webhook response
> Webhook simulate

- source/includes/_providers.md
fix #107 
---
Remove the field `Orders`.
> Provider - Remove Orders field

- source/includes/_plans.md
fix #92 
----
Add `PUT /plan/<plan_id>/items` and updates some json example
> update plan description and add put items

- source/includes/_credits.md
- source/includes/_plans.md
- source/includes/_products.md
- source/includes/_users.md
- source/index.html.md
> voucher stuff in doc

- source/includes/_orders.md
> Update Order - Credit Product and Stripe stuff

- source/includes/_metrics.md
> update Metrics - add values

- source/includes/_events.md
> update Event - EventData and update exemples

- source/includes/_intro.md
Introduce and explain how the search by *tags* works.
----
Gonna to improve typo/language ect..., would like some feedback about the structure :)
> Introduce Search by Tags

- source/includes/_events.md
Move `Previous Data` in `EventData`
> event - previous data in EventData

- source/includes/_products.md
fix #116
---
Rephrasing the `price_change_percentage`'description
> proper description of price-change-percentage

- source/includes/_users.md
Fix #121
Added note, salutation, default_payment and addresses to user attributes in several places.
> Updated user documentation

- source/includes/_users.md
> fixing data type definitions
